version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www # ✅ Mount Laravel app source code correctly
        networks:
            - laravel
        depends_on:
            db:
                condition: service_healthy
        environment:
            DB_CONNECTION: mysql
            DB_HOST: laravel_db
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    webserver:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8088:80"
        volumes:
            - .:/var/www # ✅ Ensures Laravel app is accessible
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: ${DB_DATABASE}

        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:alpine
        container_name: laravel_redis
        restart: unless-stopped
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: password
        ports:
            - "8081:80"
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
